<?php

class AddConsistency {

  private static $changes = array(
    "I/" => "i/",
    "COP" => "CoP",
    "ac-pc" => "AC-PC"
  );
  private static $correctExtensions = array(
    ".pdf", ".jpg", ".bmp", ".doc", ".docx", ".ppt", ".pptx", "gif", "bmp"
  );
  private static $possibleCorrectExtensions = array(
    ".html", ".shtml", ".php", ".html", ".phtml"
  );

  public function __construct() {
    ;
  }

  public function changeNodeAliases() {
    // get all basic page nodes
    $result = db_query("SELECT *
              FROM `node`
              WHERE `type` = 'page'");
    foreach ($result as $record) {
      $nodeObj = node_load($record->nid);
      $alias = drupal_lookup_path("alias", "node/" . $nodeObj->nid);
      echo $alias . PHP_EOL;
    }
  }

  public function checkUrlsForNodes() {
    $pages = db_query("SELECT * FROM `node`
      WHERE `type` = 'page'");
    foreach ($pages as $page) {
      $nodeObj = node_load($page->nid);
      $content = $nodeObj->body[$nodeObj->language][0]['value'];
      $this->changeUrlForTag($content, "img");
      $this->changeUrlForTag($content, "a");
    }
  }

  private function changeUrlForTag($resource, $tag) {
    $dom = new DOMDocument();
    libxml_use_internal_errors(true);
    $dom->loadHTML($resource);
    libxml_use_internal_errors(false);
    $xpath = new DOMXPath($dom);
    $srcs = $xpath->evaluate("//$tag");

    for ($i = 0; $i < $srcs->length; $i++) {
      $src = $srcs->item($i);
      if ($tag == "a")
        $attribute = "href";
      else if ($tag == "img")
        $attribute = "src";
      else if ($tag == "embed")
        $attribute = "src";
      $url = $src->getAttribute($attribute);
      if ($this->isInFileExtensions($url, AddConsistency::$correctExtensions) && strpos($url, "sites/default/files")) {
        if (!file_exists($url)) {
          $newUrl = $this->changeUrl($url);
        }
        else {
          $newUrl = $url;
        }
      }
      else {
        $newUrl = $url;
      }

      if ($this->isInFileExtensions($url, AddConsistency::$possibleCorrectExtensions) && strpos($url, "sites/default/files/imported")) {
        $newUrl = str_replace("sites/default/files/imported", "", $url);
      }
      $src->removeAttribute($attribute);
      $src->setAttribute($attribute, $newUrl);
    }
    $content = preg_replace(array("/^\<\!DOCTYPE.*?<html><body>/si",
      "!</body></html>$!si"), '', $dom->saveHTML());
    return $content;
  }

  private function isInFileExtensions($url, $fileExtensions) {
    foreach ($fileExtensions as $extension)
      if (strpos($url, $extension))
        return TRUE;
    return FALSE;
  }

  private function changeUrl($url) {
    foreach (AddConsistency::$changes as $before => $after) {
      if (file_exists(str_replace($before, $after, $url))) {
        return str_replace($before, $after, $url);
      }
    }
    return $url;
  }
}
